### ISSUE TITLE
一些问题

### ISSUE THREAD

**Issue by Kashin-J** [lscgzwd/yii2-swoole#1]
项目中还有好多阁下公司业务的代码，删的好多也没有删除干净，demo 跑不通的，还希望能再整理一下项目！

**Comment by lscgzwd** [comment]
@Kashin-J  Please try use the latest code.  I have removed all my work code. 
- just clone the latest code, and runtime.php in api/web/  with content 

```
<?php
return 'dev';
```
- execute php api/web/swoole.php start
- visit http://127.0.0.1:9501/v01/demo/index

note: you must open the redis server on you local server or change the server setting in main*.php
