### ISSUE TITLE
Latest commit not works

### ISSUE THREAD

**Issue by adonishong** [lscgzwd/yii2-swoole#2]
At first, I am sincerely appreciate for authors outcome, this project helps a lot for integrating swoole and yii2.
We have met series of issues with latest version:
1. There is no example for api/web/runtime.php, it will be better to attach a "runtime.example.php" as reference
2. It is necessary to configure these files with users environment: common/config/params-_.php, common/config/main_.php, a document about how to do so will be good for new uses
3. "v01/demo/index" mentioned by README.md is no longer exists in latest version...(we create our version reference to v23 from an elder commit)
4. "common/helpers/Trace.php" and "app/lib/Trace.php" are used in multiple places, but these files are no longer exist... (we recover this file from an elder commit)

**Comment by lscgzwd** [comment]
Please try use the latest code.  I have removed all my work code. 
- just clone the latest code, and runtime.php in api/web/  with content 

```
<?php
return 'dev';
```
- execute php api/web/swoole.php start
- visit http://127.0.0.1:9501/v01/demo/index

note: you must open the redis server on you local server or change the server setting in main*.php

Thanks your feedback.
1. doc problem, sorry for bad usage , I will and usage for this.
2. like one.
3. v01/demo/index exists in the last commit and the latest commit. I have tried it. It works ok. Please try the latest code again.
4. I have added the common/helper/Trace.php , and change or code to the new. sorry for my mistake.
